### ISSUE TITLE
Hi,I try add this sdk to my project, but got "Incompatible packages" message

### ISSUE THREAD

**Issue by wenewzhang** [ibigbug/Mixin-SDK-CSharp#5]
Hi,I want create a console demo,  try add this SDK to my project, 
Actually, I run a  VS 2017 community edition on macOS,
but got "Incompatible packages" message,
Is there any solutions for me?

Thanks

Getting restore information for project /Users/wenewzhang/Projects/demo/demo/demo.csproj
Running non-parallel restore.
Reading project file /Users/wenewzhang/Projects/demo/demo/demo.csproj.
Restoring packages for /Users/wenewzhang/Projects/demo/demo/demo.csproj...
Restoring packages for .NETCoreApp,Version=v2.1...
Resolving conflicts for .NETCoreApp,Version=v2.1...
Checking compatibility of packages on .NETCoreApp,Version=v2.1.
Checking compatibility for demo 1.0.0 with .NETCoreApp,Version=v2.1.
Checking compatibility for Microsoft.NETCore.App 2.1.0 with .NETCoreApp,Version=v2.1.
Checking compatibility for Mixin.Network 1.0.9 with .NETCoreApp,Version=v2.1.
NU1202: Package Mixin.Network 1.0.9 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package Mixin.Network 1.0.9 supports: net472 (.NETFramework,Version=v4.7.2)
Checking compatibility for Microsoft.NETCore.DotNetHostPolicy 2.1.0 with .NETCoreApp,Version=v2.1.
Checking compatibility for Microsoft.NETCore.Platforms 2.1.0 with .NETCoreApp,Version=v2.1.
Checking compatibility for Microsoft.NETCore.Targets 2.1.0 with .NETCoreApp,Version=v2.1.
Checking compatibility for NETStandard.Library 2.0.3 with .NETCoreApp,Version=v2.1.
Checking compatibility for Microsoft.NETCore.DotNetHostResolver 2.1.0 with .NETCoreApp,Version=v2.1.
Checking compatibility for Microsoft.NETCore.DotNetAppHost 2.1.0 with .NETCoreApp,Version=v2.1.
Incompatible packages: 1
Package restore failed. Rolling back package changes for 'demo'.

**Comment by ibigbug** [comment]
well, the target framework is .net472.

from the log I can see you are using .NETCore

The plan is to retarget this project against .net standard.

**Comment by wenewzhang** [comment]
Thank your,
anyway!
